# Generated by Django 5.0.2 on 2024-02-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemApp', '0003_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
